---
collections:
  - name: ansible.utils
    version: ">=2.5.0, <3.0.0"
  - name: community.general
    version: ">=4.0.0, <5.0.0"
  - name: ansible.posix
    version: ">=1.3.0, <2.0.0"
  - name: kubernetes.core
    version: ">=2.0.0, <3.0.0"
  - name: community.kubernetes
    version: ">=1.0.0, <2.0.0"
