---
apiVersion: v2
name: argo-cd
description: Helm chart for deploying Argo CD
home: https://github.com/argoproj/argo-helm
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 7.7.16
type: application
version: 7.7.16
appVersion: v2.5.3
