---
certmanager_vars:
  kubernetes:
    cainjector:
      resources:
        limits:
          cpu:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    controller:
      replicas: 2
      resources:
        limits:
          cpu:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    helm:
      chart:
        name: cert_manager
        version: v1.16.2
      repository:
        name: cert_manager
        org: jetstack
        url: https://charts.jetstack.io
    global:
      log_level: 2
    namespace: kube-system
    webhook:
      replicas: 1
      resources:
        limits:
          cpu:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
  release:
    checksum: checksums.txt
    file: cmctl_linux_arm64
    repository:
      name: cmctl
      org: cert_manager
    version: v2.1.1
