---
- name: Set certmanager_map fact
  ansible.builtin.set_fact:
    certmanager_map:
      helm:
        chart:
          reference: '{{ certmanager_vars.kubernetes.helm.repository.org }}/{{ certmanager_vars.kubernetes.helm.chart.name }}'
        repository:
          name: '{{ certmanager_vars.kubernetes.helm.repository.name }}/{{ certmanager_vars.kubernetes.helm.chart.name }}'
          url: '{{ certmanager_vars.kubernetes.helm.repository.url }}/{{ certmanager_vars.kubernetes.helm.repository.name }}'
        timeout: 5m0s
      release:
        url: "https://github.com/{{ certmanager_vars.release.repository.org }}/{{ certmanager_vars.release.repository.name }}/releases/download/{{ certmanager_vars.release.version }}"
      metrics:
        service:
          monitor:
            enabled: true
            scrape:
              interval: null
              timeout: null

- name: Set certmanager_project fact
  ansible.builtin.set_fact:
    certmanager_project:
      release:
        checksum: "{{ certmanager_map.release.url }}/checksums.txt"
        file: "cmctl_{{ cli_os | default('linux') }}_{{ cli_arch | default('amd64') }}"
        url: "{{ certmanager_map.release.url }}"
      tag: "{{ certmanager_vars.kubernetes.helm.chart.version }}"

