---
- name: Set certmanager_map fact
  ansible.builtin.set_fact:
    certmanager_map:
      helm:
        chart:
          reference: "{{ certmanager_vars.kubernetes.helm.repository.org }}/{{ certmanager_vars.kubernetes.helm.chart.name }}"
        repository:
          name: "{{ certmanager_vars.kubernetes.helm.repository.name }}"
          url: "{{ certmanager_vars.kubernetes.helm.repository.url }}"
        timeout: 5m0s
      release:
        url: "https://github.com/{{ certmanager_vars.release.repository.org }}/{{ certmanager_vars.release.repository.name }}/releases/download/{{ certmanager_vars.release.version }}"
      metrics:
        service:
          monitor:
            enabled: true
            scrape:
              interval: null
              timeout: null

- name: Set certmanager_project fact
  ansible.builtin.set_fact:
    certmanager_project:
      release:
        checksum: "{{ certmanager_map.release.url }}/{{ certmanager_vars.release.checksum | basename }}"
        file: "cmctl_{{ cli_arch | default('unknown') }}_{{ cli_arch | default('unknown') }}"
        url: "{{ certmanager_map.release.url }}"
      tag: "{{ certmanager_vars.kubernetes.helm.chart.version }}"

